### ISSUE TITLE
t/irods_groupadmin_test.t does not clean up after itself

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/perl-irods-wrap#120]
+++++++++++++++  Test Output +++++++++++++++++++++++++++++++++++
   (in WTSI::NPG::iRODS::GroupAdminTest->lg)
          got: 1
     expected: 0
   Failed test 'Has zero members initially'
   at t/lib/WTSI/NPG/iRODS/GroupAdminTest.pm line 114.
   (in WTSI::NPG::iRODS::GroupAdminTest->set_group_membership)
          got: 1
     expected: 0
 Looks like you failed 2 tests of 12.
t/irods_groupadmin_test.t .. 
+++++++++++++++  End of Test Output +++++++++++++++++++++++++++++++++++

Tests run on Jenkins as mg8, OpenStack IRODs server is used, the user has admin priv., this test was run against this server previously. On inspection, ss_0 group is left behind:

ubuntu@wipserv:~$ iadmin lg
public
rodsadmin
ss_0

**Comment by keithj** [comment]
Resolved by #121
